# git-cliff 配置文件
# https://git-cliff.org/docs/configuration

[changelog]
# 用于渲染为变更日志头部的 Tera 模板
# See https://keats.github.io/tera/docs/#introduction
#header = """
#[![animation](https://raw.githubusercontent.com/orhun/git-cliff/main/website/static/img/git-cliff-anim.gif)](https://git-cliff.org)\n
#"""
# 用于渲染变更日志中每个发布条目的 Tera 模板
# See https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}:rotating_light:[**破坏性改动**] {% endif %}\
        {{ commit.message | replace(from="<REPO>", to=self::remote_url()) | upper_first }} -\
         {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %} \
        [({{ commit.id | truncate(length=7, end="") }})]({{ self::remote_url() }}/commit/{{ commit.id }})\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [ 未发布 ]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## New Contributors ❤️
{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif %}


"""
# 用于渲染为变更日志页脚的 Tera 模板
# See https://keats.github.io/tera/docs/#introduction
footer = """
<!-- generated by git-cliff -->
"""
# 从变更日志的正文中移除开头和结尾的空白字符
trim = true
# 用于修改变更日志的一组基于正则表达式的后处理器
postprocessors = [
    # 替换占位符 `<REPO>`, 已在 Tera 模板中自动实现
    # { pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" }, # 替换仓库 URL
]
# 输出文件路径
output = "CHANGELOG.md"

[git]
# 根据 Conventional Commits 规范解析提交信息
# See https://www.conventionalcommits.org
conventional_commits = true
# 如果设置为 true，则不符合 Conventional Commits 规范的提交将被排除。
filter_unconventional = true
# 要求所有提交遵循约定式提交规范。
# 优先于 filter_unconventional。
require_conventional = false
# 按换行拆分提交，将每一行视为单独的提交
split_commits = false
# 一组用于在解析/分组提交信息之前处理提交消息的预处理器。
# 这些基于正则表达式的预处理器可用于从提交消息/正文中删除或选择某些部分，以供后续流程使用。
commit_preprocessors = [
    # 解析可能出现的 GitHub issue 链接作为占位符
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" },
    # 排除 npm version 这类自动添加版本号的 commit
    { pattern = '^(\d+.\d+.\d+)', replace = 'chore(tag): ${0}' },
]
# 一个基于正则表达式的解析器数组，用于从 commit message 中提取数据。
# 将 commit 分配到不同的分组。
# 可选地设置 commit 的范围，并可决定是否将 commit 排除在后续处理之外。
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->:sparkles: 新功能" },
    { message = "^fix", group = "<!-- 1 -->:bug: 修复" },
    { message = "^improve|^imp", group = "<!-- 4 -->:fire: 优化" },
    { message = "^refactor", group = "<!-- 2 -->:recycle: 重构" },
    { message = "^doc", group = "<!-- 3 -->book: 文档" },
    { message = "^perf", group = "<!-- 4 -->:zap: 性能" },
    { message = "^style", group = "<!-- 5 -->:art: 样式" },
    { message = "^build", group = "<!-- 5 -->:wrench: 依赖 | 构建" },
    { message = "^test", group = "<!-- 6 -->:alembic: 测试" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(tag\\)", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
    { message = "^chore", group = "<!-- 7 -->:package: 杂项" },
    { message = "^ci", group = "<!-- 7 -->:hammer: 工作流" },
    { message = "^i18n", group = "<!-- 8 -->:globe_with_meridians: 国际化" },
    { message = "^revert", group = "<!-- 9 -->:rewind: 回退" },
]
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = false
# 如果设置为 true，则不符合 commit_parsers 解析规则的提交将被过滤掉
filter_commits = false
# Regex to select git tags that represent releases.
tag_pattern = "v[0-9].*"
# Regex to select git tags that do not represent proper releases.
# Takes precedence over `tag_pattern`.
# Changes belonging to these releases will be included in the next release.
#skip_tags = "beta|alpha"
# Regex to exclude git tags after applying the tag_pattern.
#ignore_tags = "rc|v2.1.0|v2.1.1"
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# 合法值: newest, oldest
sort_commits = "newest"
