name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # 必须有写权限才能创建 release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          version: 'latest'
          args: --config-url https://raw.githubusercontent.com/NiButCrazy/nbc-auto-changelog/master/cliff.toml
        env:
          OUTPUT: CHANGELOG_NEW.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Add changelog to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          body_path: CHANGELOG_NEW.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



