name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # 必须有写权限才能创建 release

jobs:
  release:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build Windows application
        run: npm build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nbc-auto-changelog
        run: npm install -g nbc-auto-changelog

      - name: Get CHANGELOG.md content
        id: changelog
        shell: pwsh
        run: |
          nbc-auto-changelog --stdout --ending-version ${{ github.ref_name }} --starting-version ${{ github.ref_name }} | Out-File -FilePath ./changelog_new.txt -Encoding UTF8

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "AI ${{ github.ref_name }} maybe"
          body: "awdawd"
          #          body_path: ./changelog_new.txt
          files: |
            ./.out/dist/*.exe


