name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # 必须有写权限才能创建 release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Get CHANGELOG_NEW.md
        id: changelog
        run: git cliff --latest -o CHANGELOG_NEW.md

      - name: Add changelog to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          body_path: CHANGELOG_NEW.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



